# Generated by Django 2.1.3 on 2019-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.CharField(blank=True, max_length=512, null=True)),
                ('read_string', models.CharField(blank=True, max_length=64, null=True)),
                ('like_string', models.CharField(blank=True, max_length=64, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'diary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LvyouNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(blank=True, db_column='_id', max_length=256, null=True)),
                ('img_url', models.CharField(blank=True, max_length=256, null=True)),
                ('like', models.CharField(blank=True, max_length=10, null=True)),
                ('look_num', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('note_url', models.CharField(blank=True, max_length=256, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lvyou_note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('hot_rate', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('month_sold', models.IntegerField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('spot_type', models.IntegerField(blank=True, null=True)),
                ('diary_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('is_login', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_vip', models.IntegerField(blank=True, null=True)),
                ('is_manager', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
